name: Xquare Deploy for Stage
 
on:
  push:
    branches:
      - main 

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install

    - run: npm run build --if-present

    - name: Deploy to xquare
      uses: team-xquare/xquare-deployment-action@master 
      with:
        environment: stag
        access_key: ${{ secrets.ACCESS_KEY }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}